package echozapmiddleware

import (
	"bytes"
	"io"
	"net/http"
	"unicode/utf8"

	"github.com/adlandh/response-dumper"
	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func prepareReqAndResp(c echo.Context, config ZapConfig) (*response.Dumper, []byte) {
	var respDumper *response.Dumper

	var reqBody []byte

	req := c.Request()

	if config.IsBodyDump {
		if req.Body != nil {
			var err error

			reqBody, err = io.ReadAll(req.Body)
			if err == nil {
				_ = req.Body.Close()
				req.Body = io.NopCloser(bytes.NewBuffer(reqBody)) // reset original request body
			}
		}

		respDumper = response.NewDumper(c.Response().Writer)
		c.Response().Writer = respDumper
	}

	return respDumper, reqBody
}

func limitString(str string, size int) string {
	if len(str) <= size {
		return str
	}

	strBytes := []byte(str)

	if len(strBytes) <= size {
		return str
	}

	validBytes := strBytes[:size]
	for !utf8.Valid(validBytes) {
		validBytes = validBytes[:len(validBytes)-1]
	}

	return string(validBytes)
}

func limitStringWithDots(str string, size int) string {
	if size <= 10 {
		return limitString(str, size)
	}

	result := limitString(str, size-3)
	if result == str {
		return str
	}

	return result + "..."
}

func limitBody(config ZapConfig, str string) string {
	if !config.LimitHTTPBody {
		return str
	}

	return limitStringWithDots(str, config.LimitSize)
}

func getRequestID(ctx echo.Context) string {
	requestID := ctx.Request().Header.Get(echo.HeaderXRequestID) // request-id generated by reverse-proxy
	if requestID == "" {
		// missed request-id from proxy, got generated one by middleware.RequestID()
		requestID = ctx.Response().Header().Get(echo.HeaderXRequestID)
	}

	return requestID
}

func logit(status int, logger *zap.Logger, fields []zapcore.Field) {
	switch {
	case status >= 500:
		logger.Error("Server error", fields...)
	case status >= 400:
		logger.Warn("Client error", fields...)
	case status >= 300:
		logger.Info("Redirection", fields...)
	default:
		logger.Info("Success", fields...)
	}
}

func addHeaders(config ZapConfig, reqHeaders http.Header, resHeaders http.Header) []zapcore.Field {
	if !config.AreHeadersDump {
		return nil
	}

	return []zapcore.Field{
		zap.Any("req.headers", reqHeaders),
		zap.Any("resp.headers", resHeaders),
	}
}

func addBody(config ZapConfig, c echo.Context, reqBody string, respDumper *response.Dumper) []zapcore.Field {
	if !config.IsBodyDump {
		return nil
	}

	skipReq, skipResp := config.BodySkipper(c)

	var fields []zapcore.Field

	body := limitBody(config, reqBody)
	if len(body) > 0 && skipReq {
		body = "[excluded]"
	}

	fields = append(fields, zap.String("req.body", body))

	body = limitBody(config, respDumper.GetResponse())
	if len(body) > 0 && skipResp {
		body = "[excluded]"
	}

	fields = append(fields, zap.String("resp.body", body))

	return fields
}
